### ISSUE TITLE
[JOSS review]: unexpected keyword argument with feature transformations

### ISSUE THREAD

**Issue by gabrieldansereau** [earth-chris/elapid#75]
Running the Maxent vignette example (after the workaround I described in #74 to access the sample data), using the `is_features=True` flag in `model.fit` after the feature transformations returns the following error:
`TypeError: MaxentModel.fit() got an unexpected keyword argument 'is_features'`.

I get this error after running the code described in the vignette.
```python
import elapid

x, y = elapid.load_sample_data()
model = elapid.MaxentModel()
model.fit(x, y)

model.predict(x) # add

# Feature Transformations
features = elapid.MaxentFeatureTransformer()
z = features.fit_transform(x)
model.fit(z, y, is_features=True)
```

Here is the detailed output from IPython: 
```
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.6.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import elapid

In [2]: x, y = elapid.load_sample_data()

In [3]: model = elapid.MaxentModel()

In [4]: model.fit(x, y)
Out[4]: MaxentModel()

In [5]: features = elapid.MaxentFeatureTransformer()

In [6]: z = features.fit_transform(x)

In [7]: model.fit(z, y, is_features=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [7], line 1
----> 1 model.fit(z, y, is_features=True)

TypeError: MaxentModel.fit() got an unexpected keyword argument 'is_features'
```

**Comment by earth-chris** [comment]
Gah, sorry, this is something that I updated from the python API but didn't propagate through to the documentation.

Once I resolve #77, I'm thinking it's probably best to convert the documentation from Markdown to a jupyter notebook (which can be rendered in html by `mkdocs`). This would mean that you should be able to run the notebook end-to-end and verify that the functions work as advertised. The docs effectively become an integration test at that point.
