### ISSUE TITLE
[JOSS review]: data to reproduce the examples in the documentation

### ISSUE THREAD

**Issue by gabrieldansereau** [earth-chris/elapid#77]
Would it be possible to have access to data files to reproduce the examples in the documentation? For instance, the "A Simple Maxent Model" vignette uses a .gpkg and a .tif file. The "Working with Geospatial data" also uses a .shp file.

I think having completely reproducible examples would really help users understand how to use this package correctly and would help you show how useful it can be. I often find it hard to know which kind of data to use without a working example, even if it's only a basic one. 

I tried using the data in the `tests` folder as a replacement but I'm running into CRS errors. These are probably easily fixable, but I'm sure users would appreciate having a working example while learning how to use the package.

**Comment by earth-chris** [comment]
Yea, I agree that this would be very valuable for users.

I think one of the primary questions I've had is whether to a) package a full vector / raster dataset for distribution with `elapid` (which would increase the package size by several mb) or whether to post some data to an http server to demonstrate the ability to read / work with web-hosted data (which requires heavy network use if making repeated web read requests).

Perhaps the middle ground is to do something like the following:

- host a vector / raster dataset via http
- write a convenience function to download it and work with these data locally
- package a vector dataset that has been annotated with the coincident raster values

This would mean that running some of the full raster/vector operations could be done locally or remotely based on whether a user chooses to download the data. Or, the packaged version could be loaded easily and several spatially-explicit modeling tasks can be performed off-the-bat without needing to do the rote data prep steps.

**Comment by earth-chris** [comment]
The reason you're getting CRS errors with the existing `bradypus` data is that, as packaged by `maxnet`, the underlying data had no geographic data. It was just tabular. Maxent doesn't care because it's not spatial, but we care because, you know.

I'm pretty sure Elith et al. or others have published the full `bradypus` data somewhere and I'll see if I can reconcile the location data with the aspatial data.

Regardless, getting a spatially-explicit example dataset is a high priority and we'll get there one way or another.

**Comment by gabrieldansereau** [comment]
Just to chime in, your middle-ground solution seems great. I definitely understand your intent to keep the package size small and avoid heavy network use. Having the option to download it from an http server solves it.

I also think it's a great idea to document how operations can be done either locally or remotely. It makes another good selling point for the package.
