### ISSUE TITLE
Citing elapid library

### ISSUE THREAD

**Issue by aFewThings** [earth-chris/elapid#88]
Hi, I want to cite the elapid library in my paper.
Is your library plan to be published as a paper, or is there any proper way to cite elapid?

**Comment by earth-chris** [comment]
hi @aFewThings, thanks for reaching out. `elapid` has been submitted to JOSS and you can find the review [here](https://github.com/openjournals/joss-reviews/issues/4930). I'm not sure when that will wrap up. Do you have a sense for when you're planning to submit (or, when you'll need a proper DOI)?

**Comment by earth-chris** [comment]
In the short-term, I've added a file with the basic software information you can use to cite the package. Just click the link on the right-hand side of the repository to get the formatted citation:

![image](https://user-images.githubusercontent.com/10216182/221777681-a01d0aad-6af9-4879-b741-795274f3a716.png)

I'll avoid generating a DOI at this time as I'd prefer just wait until I get one from the JOSS submission.

**Comment by earth-chris** [comment]
hi @aFewThings sorry it's taken this long to get here, but `elapid` has now been published through JOSS. You can find the paper [here](https://joss.theoj.org/papers/10.21105/joss.04930). I've updated the "Cite this repository" link with the most recent information, too. I hope you find this useful. I'll close this issue unless there is more you'd need me to address.
