### ISSUE TITLE
package install challenges from `conda-forge`

### ISSUE THREAD

**Issue by earth-chris** [earth-chris/elapid#92]
@chrisborges reported the following issues when installing from conda:

> WorkingWithGeospatialData notebook is great. I was able to reproduce almost everything and enjoyed the through explanation. Unfortunately, I was not able to reproduce the histogram graph.
> some things that threw errors: TypeError: zonal_stats() got an unexpected keyword argument 'quiet'
> In both "WorkingWithGeospatialData" and "A simple maxent model" I was unable to run the merged command:
> merged = ela.stack_geodataframes(presence, background, add_class_label=True)
> Issue: AttributeError: module 'elapid' has no attribute 'stack_geodataframes'

These appear to be version issues that should be resolved in `0.3.20`. But they persisted even after running `conda update elapid`.

Unfortunately I have not been able to reproduce these errors. I was able to run each demo notebook end-to-end after installing elapid in a clean conda environment.

To diagnose, @chrisborges, would you be able to run the following?

```python
import elapid
print(elapid.__version__)
```

If the version isn't `0.3.20` then we'll want to make sure you get the latest version. To do that, you could try the following:

- `conda install elapid=0.3.20`
- or install in a clean environment using [these instructions](https://earth-chris.github.io/elapid/install/#resolving-geospatial-dependencies)

If you do have the most recent version and you're still experiencing issues then I'll have to go back to the drawing board.

**Comment by chrisborges** [comment]
Hey Chris,

So I tried running the version command and got an error
`NameError: name 'elapid' is not defined`

I later tried to install using the elapid=0.3.20 command and got this:
```
PackagesNotFoundError: The following packages are not available from current channels:
  - elapid=0.3.20
```



I think the problem might be with my OS - which is macOS Ventura. Any thoughts?

**Comment by earth-chris** [comment]
my mistake on the above, @chrisborges, it should have specified the channel to install from. please let me know if this works:

```bash
# create a fresh environment to install in
conda create -n elapid -y -c conda-forge python=3.8 mamba

# activate this new environment
conda activate elapid

# install all dependencies from conda-forge
mamba install -y elapid=0.3.20 -c conda-forge
```

The above uses `mamba` to install the conda packages, which is just a much faster version of `conda`.

**Comment by earth-chris** [comment]
@chrisborges if this is still causing issues for you please let me know. you can always fall back on the `pip` installation, which I don't believe you'll have problems with. I'd really like to unblock this soon, if possible.

**Comment by chrisborges** [comment]
@earth-chris Unfortunately, I am on a trip and will be able to try again only on monday. Sorry for this delay.

**Comment by chrisborges** [comment]
@earth-chris This did not work for me.

**Comment by earth-chris** [comment]
@chrisborges could you share any more information? error logs? methods you've tried? do you need to use the conda install? does pip install work?
